// Signals domain - the signal DEFINITION, the first-class noun the 2026-08 signals track added.
// Before this, a signal was only its rows: identity denormalized onto every `signals` row and
// wiped/rebuilt on each re-derive, so nothing could exist before its first data point and nothing
// survived its source going away (ownership had to be exiled to config/signal-owners.json). The
// definition lives OUTSIDE that blast radius: durable identity + curation, in `signals`.
//
// The crucial identity decision: **a definition's `id` IS the signal id** - one shared namespace
// with `signals.signal_id`, `initiatives.signal_ids`, alert-rule `signal_id`s and the SPA
// pickers, which is what lets all of them keep working unchanged. Dotted ids
// ('github.stars.acme') are a convention of the derived world, not a syntax; new curated
// signals take plain slugs ('mrr').

/**
 * Where a signal's identity comes from. `derived` = auto-registered by the derive machinery (its
 * id is generated by deriver code, so renaming it is refused - the next pull would re-create the
 * old id); `manual` = human-created, points arrive by hand entry (phase B2) or never.
 */
export type SignalSource = 'derived' | 'manual'
export const SIGNAL_SOURCES: SignalSource[] = ['derived', 'manual']

// interval / accumulation / direction are the slice of this vocabulary a PROVIDER's measure
// catalogue declares defaults in, so they live in @silkweave/box-provider-kit - the package a provider is
// allowed to depend on. Re-exported here so this file stays the one import site for the signal
// vocabulary and `import { SIGNAL_INTERVALS } from '@silkweave/box-core'` keeps working verbatim.
export {
  SIGNAL_ACCUMULATIONS,
  SIGNAL_DIRECTIONS,
  SIGNAL_INTERVALS,
  type SignalAccumulation,
  type SignalDirection,
  type SignalInterval,
} from '@silkweave/box-provider-kit'

import type { SignalAccumulation, SignalDirection, SignalInterval } from '@silkweave/box-provider-kit'

/**
 * Who wrote a `signal_points` row. `manual` = human-entered, durable, never machine-deleted;
 * `live` = machine-materialized (increment buckets aggregated from events today, connector output
 * later), disposable and re-derivable at will - the `signals` table's live/backfill split applied
 * at row level. `source` is part of the PK so a live write can never destroy a manual point; the
 * read path deduplicates per bucket with live-over-manual precedence (signals/points.ts).
 */
export type SignalPointSource = 'manual' | 'live'
export const SIGNAL_POINT_SOURCES: SignalPointSource[] = ['manual', 'live']

/**
 * The default channel for source-less (manual) signals. `channel` is required on every definition
 * (it is the dashboard section key AND, for derived signals, the derive-machinery join), so
 * signals with no external source need a channel of their own - one with no deriver behind it.
 */
export const MANUAL_SIGNAL_CHANNEL = 'business'

/**
 * The signal's own STANDING goal (the "$32,650 / $35K" on a card). Distinct on purpose from an
 * initiative's target, which is a campaign goal - "this body of work exists to move that number".
 * An initiative targeting `mrr` while `mrr` carries its own target is normal and correct.
 */
export interface SignalTarget {
  /** The value to reach. */
  value: number
  /** Absolute date to reach it by (YYYY-MM-DD), if time-bound. */
  by_date?: string
  /** The value when the target was set, for progress display / pace checks. */
  baseline?: number
  /**
   * When the baseline was observed (YYYY-MM-DD) - the anchor the linear-pace check needs, since a
   * baseline is a value with no date of its own. Stamped with today by the write path whenever a
   * target lands with a baseline and no `since`, so callers never have to supply it; settable by
   * hand when back-dating a target. See signals/health.ts.
   */
  since?: string
}

export interface SignalDefinition {
  /** The signal id - one namespace with `signals.signal_id` (see the header comment). */
  id: string
  /** Display name. For derived signals this is the curated override of the deriver's denormalized
   *  row label - read paths prefer it, and auto-registration never overwrites it. */
  label: string
  /** The dashboard section within the channel ("Finance", "Audience", "North Star"). */
  signal_group: string
  /** Display unit ('dl', 'posts', '$'), or null for a bare count. */
  unit: string | null
  /** Dashboard section key + (for derived signals) the derive channel that owns the rows.
   *  Source-less signals default to `business` - just a channel with no deriver. */
  channel: string
  source: SignalSource
  interval: SignalInterval
  accumulation: SignalAccumulation
  direction: SignalDirection
  /** Owning users.id. The FIRST step of ownership resolution; null falls back to the legacy
   *  config/signal-owners.json chain (channel default → account binding → unowned). */
  owner: string | null
  /** Free text: what this number means, how it is gathered, what to watch for - exactly the
   *  context an agent (or a new teammate) needs, stored where both already read. */
  description: string
  /**
   * Signal ids this one is DRIVEN BY - edges point down at the drivers
   * (`mrr.depends_on = ['churn-rate', 'new-customers']`). A curated causal claim and nothing
   * more: edges never do arithmetic; a parent's value always comes from its own data. Kept
   * acyclic and known-ids-only on write, mirroring `initiatives.blocked_by`.
   */
  depends_on: string[]
  target: SignalTarget | null
  /**
   * The provider binding (Track C): the `data_sources.id` whose sync owns this signal's live
   * points, and the provider-native measure key it subscribes to. Both or neither - CONNECTEDNESS
   * IS `data_source_id != null`, which is why `source` above stays derived|manual. A connected
   * signal is a MANUAL signal (human-named, renameable, hand-correctable) that happens to have a
   * live feed; a `derived` one may never carry a binding, since a deriver already owns its rows.
   */
  data_source_id: string | null
  measure_key: string | null
  /** Manual ordering within lists (lower first), like every other `sort` here. */
  sort: number
  created_at: string
  updated_at: string
  /** users.id that created / last edited the row; null for machine writes (auto-registration). */
  created_by: string | null
  updated_by: string | null
}

/** Partial upsert input - `id` identifies the row; any provided field overwrites, the rest persist. */
export interface SignalDefinitionInput {
  id: string
  label?: string
  signal_group?: string
  unit?: string | null
  channel?: string
  source?: SignalSource
  interval?: SignalInterval
  accumulation?: SignalAccumulation
  direction?: SignalDirection
  owner?: string | null
  description?: string
  depends_on?: string[]
  target?: SignalTarget | null
  /** Set both to bind, pass null for both to unbind (the points stay - they are real
   *  observations; they simply stop refreshing). One without the other is refused. */
  data_source_id?: string | null
  measure_key?: string | null
  sort?: number
  /** users.id performing this mutation (stamps created_by on insert, updated_by always). */
  actor?: string
}
